### ISSUE TITLE
System expat broken for autoconf builds

### ISSUE THREAD

**Issue by StefanBruens** [coin3d/coin#436]
The "--enable-system-expat" configure option has no effect.

Disabling the bundled expat is intended to work by making the libexpat.la essentially an empty libtool library:
https://github.com/coin3d/coin/blob/f2248370cf3e44c20ea97004f5971eae358473bd/src/xml/expat/all-expat-c.c#L1-L9

Unfortunately, `USE_SYSTEM_EXPAT` is the Makefile variable (which is not defined in config.h), the correct variable from config.h is `HAVE_SYSTEM_EXPAT`:
https://github.com/coin3d/coin/blob/f2248370cf3e44c20ea97004f5971eae358473bd/src/config.h.in#L318-L319

This was never working, since the initial addition of the config option:
https://github.com/coin3d/coin/commit/55fb679b382bd3a81b650a95789a30f3486ce0e6

It is also missing to add a `-lexpat` when linking libCoin.

CMake builds seem to be correct, https://github.com/coin3d/coin/commit/d895a86164dc17cc867f0e20dadb1aba43992745, as it changes the target_link_library based on the option setting.

**Comment by StefanBruens** [comment]
This patch solves the problem for me:

[0001-Actually-link-to-system-expat.txt](https://github.com/coin3d/coin/files/5692423/0001-Actually-link-to-system-expat.txt)

Caveats:
- It only patches Makefile.in, not Makefile.am, as I was not able to run autoconf/automake without errors (even after installing simmacros).
- Only tested for Linux

**Comment by VolkerEnderlein** [comment]
Thanks for your issue report and the accompanying patch. It is highly appreciated.
We will check the patch and keep you informed. 
According to your caveats: I had a hard time to properly set up my environment to run Autotools on Coin as the scripts require some outdated version (mostly because of the Win32 compilation under Cygwin). There was an attempt to get rid of that but as we switched over to CMake it was stopped and now this is only kept in maintenance mode.

**Comment by VolkerEnderlein** [comment]
Just merged a patch for this issue. Please report back whether it fixes your issue, as I have solved it somewhat different from your proposal. Thanks for your contribution to Coin development, it is highly appreciated.
