### ISSUE TITLE
coin 4.0.3 not ABI compatible with 4.0.2?

### ISSUE THREAD

**Issue by hobbes1069** [coin3d/coin#528]
In preparing a build for Fedora `abipkgdiff` shows the following:

```
================ changes of 'libCoin.so.80.0.2'===============
  Functions changes summary: 3 Removed, 0 Changed (153 filtered out), 0 Added functions
  Variables changes summary: 0 Removed, 0 Changed (4 filtered out), 0 Added variables

  3 Removed functions:

    [D] 'method void SoRenderManager::attachClipSensor(SoNode* const)'    {_ZN15SoRenderManager16attachClipSensorEP6SoNode}
    [D] 'method void SoRenderManager::detachClipSensor()'    {_ZN15SoRenderManager16detachClipSensorEv}
    [D] 'method void SoRenderManagerP::updateClippingPlanesCB(SoSensor*)'    {_ZN16SoRenderManagerP22updateClippingPlanesCBEPvP8SoSensor}

================ end of changes of 'libCoin.so.80.0.2'===============
```

Removed functions would typically require a SONAME bump. Is this release expected to be ABI compatible?

**Comment by VolkerEnderlein** [comment]
Thanks for notifying us. This is definitely not intended. I will come up with a proper solution ASAP. Cheers.

**Comment by Rexbas** [comment]
@VolkerEnderlein, I guess I broke it in #509. Commit 5726c8805a48e39ca6778403960598346729cad6 moved the call of `setClippingPlanes()` to another place to fix an issue. This made the `clipsensor` obsolete thus I removed it in commit 7ee8ef260a69df522cb0df1d1bd2a807a6a97405. Because of this, `SoRenderManagerP::updateClippingPlanesCB()` was no longer used and both `SoRenderManager::attachClipSensor()` and `SoRenderManager::detachClipSensor()` simplified to empty methods so I also removed them.

Maybe we can bring `updateClippingPlanesCB()` back as it was. We could also add  `attachClipSensor()` and `detachClipSensor()` as empty methods. We would never call these three methods but this would restore ABI compatibility right?

**Comment by VolkerEnderlein** [comment]
@Rexbas That's what I am doing right now. I will withdraw the 4.0.3 and publish a corrected version tonight. Thanks.

**Comment by VolkerEnderlein** [comment]
@Rexbas @hobbes1069 The ABI braking changes have been reverted and the version 4.0.3 has been re-released.

**Comment by hobbes1069** [comment]
Thanks for taking care of it quickly! I'm not sure if it would have caused any real issues but better safe than sorry.
